f = open("sample.txt", "r")
data = f.read()
characters = len(data)
words = len(data.split())
lines = len(data.splitlines())
print("Total Characters:", characters)
print("Total Words:", words)
print("Total Lines:", lines)
f.close()